import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {SessionProvider} from "next-auth/react";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PIL Gaming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SessionProvider session={session}>
    <html lang="en">
      <Toaster/>
      <body className={inter.className}>{children}</body>
    </html>
    // </SessionProvider>
  );
}
